version: '3.8'
services:
  flask_app:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: '2048M'
    volumes:
      - .:/app #to mount my directory so i can update the code without stopping the container
    environment:
      - FLASK_ENV=development # for auto reloading when i do some changes on my directory
    expose:
      - "5000"
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '512M'
    ports:
      - "80:80"
    depends_on:
      - flask_app